### ISSUE TITLE
'servicechanged' and 'onservicechanged' naming is misleading

### ISSUE THREAD

**Issue by efullea** [sysapps/telephony#100]
should be 'defaultservicechanged' and 'ondefaultservicechanged' to reflect that it relates to the default service

**Comment by marcoscaceres** [comment]
I would not be in favor of this change, even though you are technically correct. "ondefaultservicechanged" that looks like an excessive amount of typing and is fairly illegible.

**Comment by zolkis** [comment]
Technically it means the underlying service has changed, i.e. a dial() method on TelephonyManager will be made on a different service. I would also leave it as it is.

**Comment by efullea** [comment]
OK, let's leave it as it is.
