### ISSUE TITLE
rename 'active' state to 'connected' state 

### ISSUE THREAD

**Issue by jmcanterafonseca** [sysapps/telephony#11]

**Comment by zolkis** [comment]
Rejected. 'Active' is the name used in standards, and it is the intended meaning of the state: the call is connected and active. A call on hold is also connected. Please check and ack.

**Comment by marcoscaceres** [comment]
Reopening. We should really do what is best for developers, not what is in standards that developers won't read. If you feel that "active" is the right thing for developers, please close again. Personally, it think connected makes more sense from a developer standpoint.

**Comment by jmcanterafonseca** [comment]
oh absolutely. onactive seems totally broken and unusable

2013/4/15 Marcos Caceres notifications@github.com

**Comment by marcoscaceres** [comment]
heh, well, I wouldn't go as far as saying "totally broken and unusable". But it does raise an eyebrow in what it could mean in the mental model of a telephone call :)

**Comment by zolkis** [comment]
Yes, exactly for the sake of the intended developers, 'active' makes more sense.
'connected' is erroneous, for reasons outlined above.
'active' is correct. Both telecoms specs and middleware implementations use that. For dialer developers, who have to know telephony (for certification reasons), it is more correct to use 'active'.
If you don't like it, please suggest alternatives.
We should not spend too much time on this...

**Comment by marcoscaceres** [comment]
@zolkis. agree, we should not bikeshed too much. I fear that it will come up again so it's good to be prepared: 
1. You state, "oth telecoms specs and middleware implementations use that". It would be good to have a ready list of specs to point to (or quotes from the specs), if you don't have those already. That gives the claim credibility and clarifies why "active" was chosen over "connected". 
2. If it's not already in the spec, the justification you give above should be included in a Note.  

Dumb question: a call on hold is connected and active, right?

**Comment by zolkis** [comment]
A call on hold is connected (from signaling point of view) and not active, because call states have 3 dimensions: call control, hold control, multiparty control.
The GSM spec suite I refer to is included in the spec (to be moved to references). Yes, they ALL use 'active'.
Introducing another term would create confusion.
My policy is to use the telephony terms, and if someone has doubts, should raise an issue, like now.
But if I start to justify all these small well known details, we'll never do this spec.

**Comment by marcoscaceres** [comment]
Thanks for the clarification. Ok, just keep in mind that a few of us here are new to the telephony side of things, so please be patient when we ask questions (well, probably just me :)). As you say, there are always good reasons for why things are named the way they are, but we need to make sure WG members understand the rationale and that we make sure developers who might have had little exposure to this stuff also "get it" (i.e., by clarifying decisions if need be in the spec).  

If you need a hand with generating the references, just send me the URLs. I have a somewhat crappy tool that can be used to generate the references for inclusion in Repec.js:

http://marcoscaceres.github.io/bib_entry_maker/

We should file a separate bug for that. With regards to speed of standardization, helping each other where we can as we go along will keep us on track.

**Comment by zolkis** [comment]
I think what would be helpful here is to invite telephony experts who would review/cross-check these kind of issues (and anyone could of course continue to raise issues). But as Bryan pointed out on the mailing list, there is no point in starting lengthy education/re-education in telephony, it is too big for that, and it is driven by standards. In addition, the targeted developers are _dialer_ developers.
GSM TS 23.018 Basic call handling; Technical realization
      http://www.3gpp.org/ftp/Specs/html-info/23018.htm
IMS TS 23.228 IP Multimedia Subsystem (IMS); Stage 2
      http://www.3gpp.org/ftp/Specs/html-info/23228.htm

**Comment by marcoscaceres** [comment]
@zolkis thanks for the links. I'll generate the references.

**Comment by zolkis** [comment]
Thanks Marcos, this is _very_ helpful. Others will need this, as well (e.g. NFC guys have just asked).

**Comment by marcoscaceres** [comment]
I need a "key" for the "Basic Call Handling". Would [[GSM-CALL]] be ok?

**Comment by marcoscaceres** [comment]
Here is the first:

``` JSON
  "GSM-CALL": {
    "authors": ["Bruno Landais"],
    "date": "28 April 1999",
    "href": "http://www.3gpp.org/ftp/Specs/html-info/23018.htm",
    "publisher": "3GPP",
    "status": "Technical realization",
    "title": "GSM TS 23.018 Basic call handling"
  }
```

**Comment by marcoscaceres** [comment]
The publisher is actually "3GPP", right?

**Comment by marcoscaceres** [comment]
Here is a proposal for the second reference. Please feel free to edit:

``` JSON
  "IMS": {
    "authors": ["Thomas Towle"],
    "date": "14 March 2002",
    "href": "http://www.3gpp.org/ftp/Specs/html-info/23228.htm",
    "publisher": "3GPP",
    "status": "Stage 2",
    "title": "IP Multimedia Subsystem (IMS)"
  }
```

**Comment by zolkis** [comment]
Yes, 3GPP is the publisher.
I also used ETSI specs, I will send a list of few links later.

**Comment by marcoscaceres** [comment]
@zolkis when you can, please file a separate bug for the ETSI specs. I've [sent a PR to Respec](https://github.com/darobin/respec/pull/205) for the two refs above.

**Comment by zolkis** [comment]
@marcoscaceres Thank you for fixing the refs. I think the GSM-CALL is enough reference for now. The ETSI specs are the same, just collected in a different way.

**Comment by zolkis** [comment]
I am closing this issue, with the resolution to keep the 'active' call term for a connected call which also has the media resources. A call on hold is also a connected call, without media resources.

**Comment by marcoscaceres** [comment]
@zolkis no probs. Happy to help.
