### ISSUE TITLE
Transition to `noLegacyStyle`

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/telephony#113]
To remove duplicate text in the spec, it would be good to use Respec's `noLegacyStyle`. 

Although this would not change the substantive content of the spec, it does mean shifting a lot of markup around, which means that merges between old and new version of the spec will be "fun" (specially if patches start coming in during the transition period). I estimate that it should take max 3 days to shift the content around (maybe just 1 day if we are lucky). 

To avoid issues, it is best to do this in one go, but after we publish as a FPWD (i.e., on or immediately after the 18th of June). 

Does that work for everyone? I (@marcoscaceres) am happy to make the changes and will begin work on this next week unless someone objects.

**Comment by zolkis** [comment]
It is a lot of work, and I agree it is kind of critical section, so it would be good if someone takes it, works on it, pushes it just as you say. We could establish a fire-break between 18 and 24 June.

**Comment by efullea** [comment]
Sounds good. Thanks Marcos.

**Comment by marcoscaceres** [comment]
Work started.

**Comment by marcoscaceres** [comment]
This task going to generate a lot of bugs, so I'm going to convert it to a milestone.

**Comment by marcoscaceres** [comment]
Editors: 

So, I initially thought I should do the noLegacyStyle transition as a single work item, but given the volume of material being shifted around (and bugs generated as a result), I've decided to spin off a new branch (`noLegacyStyle`). My rationale for doing that is: 
1. keep the current published editor's draft legible. 
2. allow for smaller pull requests. Otherwise, it's going to be impossible to review changes I'm making.  

My plan of attack is to basically start checking in what I have so far (which is going to look like a mess! but don't worry), and then start patching the changes based on bug in GH. That should keep things manageable and will allow us to keep a good record of what changed - while also not making a mess of the current Editor's draft.   

Once we are happy, everything in the `noLegacyStyle` branch will get merged back into the `gh-pages` branch.

Hope that makes sense :)

**Comment by zolkis** [comment]
Yes, it's the way such change is done best.

Zoltan
