### ISSUE TITLE
Do we need onservicechanged?

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/telephony#128]
If we have onserviceadded and onserviceremove, then why do we need onservicechanged?

**Comment by marcoscaceres** [comment]
ah, crap... got bit by the naming :)

**Comment by marcoscaceres** [comment]
Actually, we should rename this one `ondefaultchanged`

**Comment by efullea** [comment]
+1 to change it. I proposed it in #100 and a week after discussing it, it is already causing confusion.

**Comment by marcoscaceres** [comment]
heh, yeah :) it made sense the other day to keep it for some reason. Looking at it independently it seems ok, but when looked at in the context of the other two names, it gets confusing.

**Comment by marcoscaceres** [comment]
Actually, if we have `defaultServiceId`, then we don't need the events, because one can just `Object.observe()` defaultServiceId.

**Comment by zolkis** [comment]
Object.observe() is a good pattern, finally. We should spread its use in the spec...

**Comment by marcoscaceres** [comment]
I'm asking if it's something we can use... by doesn't seem we can watch properties, only simple objects :( 

Started a thread here: 
http://lists.w3.org/Archives/Public/public-script-coord/2013AprJun/0702.html

**Comment by marcoscaceres** [comment]
Looks like no go on object.observe. Closing this bug. Will update the name of the event handler attribute.
