### ISSUE TITLE
Not entirely clear what the relationship is between an app, the user agent, and a telephony service

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/telephony#140]
The spec assumes that all telephony services are available to an application. Although this is generally true, it might be that some user agent may not have access to all the telephony services. 

Can we instead say that:

> A can user agent can access zero or more telephony services of the device. Which telephony services are available to the user agent is dictated by policy, or by the user  choosing which services are available to the user agent.

**Comment by zolkis** [comment]
This is a new use case, and not the original intent of the API.
But since this is more generic, it is fine to have it this way.

However, we should add this as a use case / requirement, and to add the API (not on this spec) so that the user could control which services can be seen by the app.
