### ISSUE TITLE
TelephonyManager needs to be converted to `noLegacyStyle`

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/telephony#141]
Basically, all the `dd` become paragraphs...

**Comment by marcoscaceres** [comment]
Work in progress...

**Comment by anssiko** [comment]
@marcoscaceres Let me know if you run into any undocumented issues with the conversion, so that I can update the noLegacyStyle docs accordingly.

**Comment by marcoscaceres** [comment]
@anssiko so far so good... I think :)
