### ISSUE TITLE
 TelephonyErrorEvent is defined by never used

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/telephony#144]
The `TelephonyErrorEvent` is defined in the spec, but not used in any algorithm. I assume it will be usable in some general error handling cases. However, are not all errors represented by a state (i.e., telephonyCall.state attribute)? 

If so, we can fire a simple event named `error` at the telephonyCall object and the developer can check the state of the call to determine what the error was. Like this:

``` JS
call.onerror = function(){
   console.log("Error: " + this.state)
}
```

**Comment by zolkis** [comment]
Some reason of the error should be carried with the event, because state may change asynchronously (depending on implementation).

**Comment by marcoscaceres** [comment]
We can specify that asynchronous change can only happen on the next spin of the event loop. That way, it can avoid the race condition.  I think we need to do this regardless, otherwise things will get weird.

**Comment by marcoscaceres** [comment]
So, I'm inclined to drop TelephonyErrorEvent. We need to write the spec so that the state can't change before it is observed by an event handler. I'm pretty sure this is the default behavior in the platform (e.g., XHR behaves this way).

**Comment by zolkis** [comment]
OK.
