### ISSUE TITLE
TelephonyEvent and TelephonyCall

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/telephony#145]
I'm not really getting the use case for TelephonyEvent with the TelephonyCall interface? The ondisconnect event handler is defined as needing it. I think a simple event there would work just as well: 

``` JS
call.ondisconnected = function (e) {
  console.log("call disconnected at time" + e.timeStamp);
}
```

**Comment by marcoscaceres** [comment]
Side note: maybe "disconnected" should be "disconnect"?

**Comment by marcoscaceres** [comment]
Ignore my comment above... I see the states are transitional.

**Comment by zolkis** [comment]
Yes, a simple event should work.

**Comment by marcoscaceres** [comment]
Ok, will update.
