### ISSUE TITLE
CallHistoryEntry should probably be removed from the spec

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/telephony#155]
CallHistoryEntry is not currently used in the spec (and is marked as informative). Why don't we move it out of the spec and bring it back if we defined a call entries database of some kind?

**Comment by zolkis** [comment]
Based on my experience this is important information for people interested in dialers. IMO it should stay there as informative section. It gives a better understanding of the API and scope, and clears a few questions ahead.

**Comment by marcoscaceres** [comment]
Yeah, I totally agree that it's important. What I'm proposing is that we spin off a separate spec for it that we can build into a Calls DB - or into a separate Note (referenced from the Telephony Spec). What worries me right now is that it's kinda incomplete and leaves the reader wondering how it relates to the rest of the API (as there is no way to actually make use of it).

**Comment by marcoscaceres** [comment]
Ok, so for now I'm going to remove the use of RFC2119 keywords from the section. I've also moved it to the appendix and tried to separate out a bit so it doesn't look so much like a normative part of the spec.
