### ISSUE TITLE
Error steps not needed

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/telephony#164]
The spec states in various places (paraphrase): 

> If during further steps for call... there is an error, execute the error steps.

However, error steps state that:

> The error name, together with the call state determine the error condition.

Hence, all error conditions are tied to some known state. If that is the case, then each algorithm should deal with throwing an error explicitly for a particular error condition (and the error steps are not needed).

**Comment by zolkis** [comment]
Sounds OK.

**Comment by marcoscaceres** [comment]
Work in progress
