### ISSUE TITLE
Ovelap in dialed and connected states

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/telephony#167]
The spec defines the `dialing` state as: 

> An outbound call that has been dialed **and is being connected**.

But then "connecting" is defined as:

> A request to establish the call has been made and it is progressing.

Can we drop "and is being connected" from `dialing`?

**Comment by marcoscaceres** [comment]
Note that some are defined as something that is "going to happen/is happening", like:

> holding: The call is being put on hold.

**Comment by zolkis** [comment]
Yes, it would be correct to drop it.

**Comment by marcoscaceres** [comment]
ok, will drop it.
