### ISSUE TITLE
State wording present and past

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/telephony#168]
The spec says:

> dialing: An outbound call that has been dialed and is being connected. 

Seems weird that "dialing" is defined as something that has already happened ("call that has been dialed")? Should that not be:

> dialing: An outbound call that is being dialed by a telephony service.

**Comment by zolkis** [comment]
'dialing' just states that the user has pressed the button, but not necessarily that the telephony service already started connecting (which will also happen a few ms later).
So
1. user presses button
2. state changes to 'dialing'
3. telephony service starts dialing
