### ISSUE TITLE
ICC-ID as the service identifier? 

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/telephony#170]
The spec says:

> For SIM cards, this can include the ICC-ID as the service identifier

Does that mean that for SIM Cards, it is recommended that the ICC-ID be used as the service id in the API?

**Comment by zolkis** [comment]
The requirement is uniqueness, and ICC-ID is good for that in the case of SIM card.

**Comment by marcoscaceres** [comment]
Ok, will recommend the use of ICC-ID for when there is a SIM card.
