### ISSUE TITLE
Which task queues to use?

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/telephony#18]
There are places in the spec where events are being generated and then queued, but no particular task queue is specified. We need to check if we can hook into existing task queues or if we need to define a new one.

**Comment by zolkis** [comment]
One design point in that is the requirement to be able to give telephony related processes/tasks higher priority (e.g. using cgroups), even to the extent to freeze other processes competing for the same resources as telephony.

**Comment by marcoscaceres** [comment]
Ok, we might have a telephony task source. Should speak to @sicking, @cdumez, @mounirlamouri to see if task queues are just mythical spec things or if they are actually reflected in browser implementations.

**Comment by marcoscaceres** [comment]
Going to add:

> The task source for all tasks queued in this specification is the Telephony task source.

**Comment by marcoscaceres** [comment]
work in progress
