### ISSUE TITLE
Dial and telephone number format

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/telephony#189]
In the dial method, it's not well defined that it's the telephony service that handles invalid phone numbers.

**Comment by zolkis** [comment]
We need to specify the valid formats with references. In this version of the spec we support GSM and CDMA. In subsequent versions SIP and XMPP calls may be supported. All this have well defined remote party formats (will need to find the exact references).

**Comment by marcoscaceres** [comment]
I tried feeding the iOS a random string... it converts it all to numbers :) Weird.

**Comment by zolkis** [comment]
OK, some implementations may want to add skype, too. Other formats may be supported by some implementation, but that is the decision of the implementation, and it would not be compliant. Such apps may fail on other implementations.

**Comment by marcoscaceres** [comment]
I think this is then best left to the backend, right?

**Comment by zolkis** [comment]
The advantage of tel URI's is that all this is standardized.

**Comment by marcoscaceres** [comment]
Excuse my ignorance, but what does an XMPP number(?) look like?

**Comment by zolkis** [comment]
http://xmpp.org/rfcs/rfc6122.html

**Comment by zolkis** [comment]
> I think this is then best left to the backend, right?

It depends whether do we require implementations to validate user strings for security reasons, or do we push that to the backends. We could do a pre-validation (length, encoding etc), and leave the rest to the backends.

**Comment by marcoscaceres** [comment]
I think for V1 we should just leave it all to the backends and see how we go... if people complain during review, we can start imposing rules.

**Comment by zolkis** [comment]
OK. We can create a note, eventually.

**Comment by marcoscaceres** [comment]
Clarified this in https://github.com/marcoscaceres/telephony/commit/4e876273a474f1752a352dc03b67ff3809870793

**Comment by zolkis** [comment]
Closing.
