### ISSUE TITLE
Invoking dial() twice should result in an AbortError

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/telephony#191]
In the dial() method, the spec says: 

> If calls array already contains a TelephonyCall object with identical remoteParty attribute, then an InvalidModificationError exception.

The InvalidModificationError seems a bit illogical here, as the developer doesn't know that some internal array is being modified in an invalid way. 

This should really be an "AbortError" IMO ("The operation was aborted.").

**Comment by zolkis** [comment]
OK.

**Comment by marcoscaceres** [comment]
It should be possible for a use to place a call to the same number through different telephony services, no? Kinda silly, but possible.

**Comment by zolkis** [comment]
Yes, I agree, one could call a number with GSM, and with Skype Out, the latter will signal busy. The API should not stop this behaviour.
