### ISSUE TITLE
Dial method needs rewrite

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/telephony#193]
There are a number of issues with the dial steps as currently written. They don't properly define synchronous and async actions (e.g., when to return). The method creates objects prematurity; doesn't properly associate telephony service with a call, etc. 

Basically, it needs a bit of a rewrite :)

**Comment by marcoscaceres** [comment]
Work in progress...

**Comment by zolkis** [comment]
See also my more detailed steps described at issue #17.
