### ISSUE TITLE
calls attribute of the TelephonyManager interface should be a sequence

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/telephony#194]
The calls attribute of the TelephonyManager interface needs to be redefined as a method "getCalls()".  

See discussion in:
- https://github.com/sysapps/telephony/issues/133
- https://github.com/sysapps/telephony/issues/81
- [discussion on public-script-coord](http://lists.w3.org/Archives/Public/public-script-coord/2013AprJun/0748.html)

**Comment by marcoscaceres** [comment]
work in progress

**Comment by zolkis** [comment]
Gardening? :)

**Comment by marcoscaceres** [comment]
yep... closing things still assigned to me :) .... oh, so many memories
