### ISSUE TITLE
dial() method needs to treat null as empty string

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/telephony#196]
Calling dial(null) results in null being converted to "null", which will be passed to the telephony system to deal with. It would be better to at least have it automatically converted to an empty string in WebIDL:

``` WebIDL
TelephonyCall dial ([TreatNullAs=EmptyString] DOMString remoteParty, optional DialParams params);
```

The dial() method needs to be redefined as treating null as an empty string. And the prose needs to say what to do with an empty string.

**Comment by zolkis** [comment]
Agreed.

**Comment by zolkis** [comment]
Closing.
