### ISSUE TITLE
CallHandler should be "implemented", not inherited

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/telephony#23]
CallHandler is superfluous in the spec at the moment, as it's used by two interfaces that don't actually need to inherit it. It is superfluous is that it cannot be used on it's own, so it's really just an abstract base class. 

To fix this, we have two options: 
1. copy/paste everything from CallHandler to the inheriting interfaces (this will bloat the spec a bit).
2. Keep the current design, but instead of inheriting from CallHandler, make TelephoneCall and Conference Call "implement" CallHandler. 

In 2. All that needs to change in the spec is:

``` JS
interface TelephonyCall {
 ... all the same...
}
TelephonyCall implements CallHandler; 

interface ConferenceCall {
 ... all the same...
}
ConferenceCall implements CallHandler;
```

Then, CallHandler can remain a [NoInterfaceObject].

**Comment by marcoscaceres** [comment]
See the following link for details of "implements" and examples: 
http://dev.w3.org/2006/webapi/WebIDL/#idl-implements-statements

**Comment by zolkis** [comment]
Thank you Marcos, you are very helpful, as always. I will do this.

**Comment by marcoscaceres** [comment]
work in progress...
