### ISSUE TITLE
Recommend default values

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/telephony#34]
For where "If not specified, the implementation MUST provide a default value" appears, the specification should provide recommended values. 

This includes ToneParams:
- duration
- gap

(there may be others)

**Comment by marcoscaceres** [comment]
Q.23 doesn't seem to say how long the duration and gap need to be :( 

However, Wikipedia states that, for country specific tones: 

>  The duration of the tone should be at least 70 ms, although in some countries and applications DTMF receivers must be able to reliably detect DTMF tones as short as 45ms.

**Comment by zolkis** [comment]
IMO this should not be specified, the implementation owns the defaults.

**Comment by marcoscaceres** [comment]
Right, but this is more to help developers so they know what to expect. They are soft recommendations based on whatever the industry standard is for each.

**Comment by marcoscaceres** [comment]
I'm closing as invalid.
