### ISSUE TITLE
Markup comments - do we still need them?

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/telephony#50]
The current spec contains a whole bunch of stuff that has been commented out, which makes the spec difficult to edit. Why not delete each comment as a commit? then we have a record that we can search if we want to bring anything back. 

If it's ok, I would like to remove the unnecessary comments as described above.

**Comment by zolkis** [comment]
Some of those comments are meant to be there, like call states in GSM, CDMA, then TelephonyService, references to standards, etc. Some others can be removed, like event handlers and other similar stuff.

**Comment by marcoscaceres** [comment]
So, I removed the dead interfaces and other minor things. Left all the important ones... we should look at making them part of the actual spec, if they are not already.
