### ISSUE TITLE
Attributes, getting and setting

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/telephony#51]
The spec is somewhat inconsistant about getting and setting attributes. It would be nicer if when getting an attribute, the spec said "When getting, the user agent MUST bla bla". Same for attributes that can be set. This would integrate the spec more nicely with WebIDL's algorithms.

**Comment by marcoscaceres** [comment]
work started.

**Comment by marcoscaceres** [comment]
did some more work on this as part of #64, but still have a few more to do.

**Comment by zolkis** [comment]
For readonly attributes, does it add any information saying "When getting, it MUST return..." instead of saying "It MUST return"?

**Comment by marcoscaceres** [comment]
Yes, because of the way they are reflected in javascript. "Getting" maps to an actual getter - when the spec talks about getting (but not setting), an implementer reads:

``` JS
var someValue; 
Object.defineProperty(o, "theAttribute", {
    get: function () {
      return someValue;
    },
    set: undefined,
    enumerable: true,
    configurable: true
  });
```

**Comment by marcoscaceres** [comment]
@zolkis but technically, you are correct - it just makes the spec more consistent and easier to implement because it maps 1 to 1 to concepts in WebIDL and JavaScript.

**Comment by zolkis** [comment]
OK, I will finish up the rest, and fix the rest of issues linked to FPWD. Thanks for the lot of work you've done so far.

**Comment by marcoscaceres** [comment]
no probs. I'm just finishing up some stuff over on manifest and was planning to jump back into telephony. If there is anything in particular you want me to work on, please assign it to me.

**Comment by zolkis** [comment]
Marcos, please check.

**Comment by marcoscaceres** [comment]
will check first thing tomorrow.

**Comment by marcoscaceres** [comment]
Continuing to work on these...
