### ISSUE TITLE
How does a call become "managed" by TelephonyManager? 

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/telephony#52]
For TelephonyManager's `readonly attribute Call[] calls`, the spec says:

> When getting, the user agent MUST return an array containing zero or more Call objects managed by this object. Note that TelephonyCall objects belonging to a multiparty call are managed by the corresponding ConferenceCall object and MUST NOT be also present in this array.

It's not clear from the above how a Call became "managed" by the TelephonyManager. That is, with respect from differentiation with ConferenceCall objects that are not in the list.

**Comment by zolkis** [comment]
"Managed" means that the only way to get/list a call object is via the interface which manages the call, which can be TelephonyManager or ConferenceCall.
Conference calls in fact are specialized call managers, not calls per se.
This comes from the way conf calls are specified in GSM.
For instance, multiparty call states are orthogonal to call states.

In this sense, we could rename ConferenceCall to ConferenceManager.
However, a ConferenceCall can be put on hold and resumed, just like a TelephonyCall.
