### ISSUE TITLE
Do we need "readonly attribute boolean conference"?

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/telephony#55]
It's possible to check if a TelephonyCall is a conference call by doing an instanceof check:

``` JS
if (someObject instanceof ConferenceCall){
   ...
}
```

hence I don't think we need "readonly attribute boolean conference".

**Comment by zolkis** [comment]
The semantics is that the TelephonyCall is managed by a conference call, hence it's mostly "read-only", with methods blocked, except disconnect(). It is not an instance of ConferenceCall.

**Comment by marcoscaceres** [comment]
Ah! Sorry - totally missed that as I haven't gotten reviewing conference calls yet! 

This returns true if the TelephonyCall is in the "calls" list for the ConferenceCall. Ok, the spec is wrong then, IMO. Need to move "conference" attribute to the TelephonyCall interface instead of the CallHandler interface. Or can you see any use case for the ConferenceCall have a conference attribute also? 

We should also rename this "inConference", otherwise it sounds weird for a boolean attribute.

**Comment by zolkis** [comment]
'inConference' sounds good.
The instanceof covers the other half.

**Comment by marcoscaceres** [comment]
work in progress...
