### ISSUE TITLE
Error attribute of CallHandlers is redundant

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/telephony#56]
The use of a "readonly attribute DOMError error" on an *Manager doesn't seem like a good construct. Errors should only result from operations or from an event (i.e., shouldn't be part of an manager interface). 

I recommend we remove "readonly attribute DOMError error" and make sure that errors go to error handlers or are thrown as exceptions if sync (or are handled by a Future, if we end up using those).

**Comment by zolkis** [comment]
If you speak about TelephonyManager, you are probably right.

But TelephonyCall is actually a specialized async handler, where Futures are generic ones. It manages its own state and part of that is error management. Preferably exceptions are avoided in TelephonyCalls, every error case should be managed by the error attribute and a signal.

ConferenceCall is manager and call handler in the same time, so a bit of a mix, but I think it should handle errors the same way as TelephonyCall. I will check and re-think this. The whole multiparty call area needs some rethinking.

**Comment by marcoscaceres** [comment]
> every error case should be managed by the error attribute and a signal.

So, on CallHandler currently we have both:

``` JS
readonly attribute DOMError error;
attribute EventHandler onerror;
```

Assuming that error attribute contains the error object, then that could lead to a race condition: the developer might need to update the UI asynchronously, in which time another error could occur in which case they will miss the first error. 

Like:

``` JS
call.onerror = function(){
    $("ui").fadein(500).then(showError(this.error))
}
```

Better would be if we defined a TelephonyErrorEvent that has its own Error object. 

``` JS
TelephonyErrorEvent : Event{
   readonly attribute DOMError error; 
}
```

The example would then look like this:

``` JS
call.onerror = function(e){
    $("ui").fadein(500).then(showError(e.error))
}
```

**Comment by zolkis** [comment]
I agree, let's do that.

**Comment by marcoscaceres** [comment]
work started.
