### ISSUE TITLE
serviceIds and defaultServiceIds have one too many ";"

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/telephony#6]
There is a typo in the WebIDL where TelephonyManager's serviceIds and defaultServiceIds attributes have one too many ";"

**Comment by zolkis** [comment]
Fixed.

**Comment by marcoscaceres** [comment]
@zolkis please be sure to close bugs through pull requests. Otherwise, we don't have a record of what commit closed what bug. Please alway be sure that your pull requests are reviewed by at least one person (e.g., the person who filed the bug).

**Comment by zolkis** [comment]
I have included the issue number and link to the commit comment. As I am the committer, I could file a pull request to myself, which I can do next time - or should I fork your repo, file a PR to you, then you'd file a PR to the committer (me)?

**Comment by zolkis** [comment]
Actually, if we want to track issues, we must mention the issue number in the commit messages for sure, then of course we could also use pull requests and leaving time for review.

**Comment by marcoscaceres** [comment]
The way I do it is:
1. fork the repo from sysapps to my own space on GH.
2. make changes. 
3. send PR back to sysapps. If the PR is closing some particular bug, I just say "potentially closes #X". 
4. wait for integrator (or others in the WG) to review - accept/reject. 
5. if accepted, then the bug addressed in the PR is also be closed. 

So, yeah, mentioning the issue number is good because GH automagically associates them together.
