### ISSUE TITLE
Use HTML5 Tidy

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/telephony#63]
The spec is fairly liberal in it's coding style - which means indenting if kinda all over the place. It would be great if we could just run [HTML5 tidy](https://github.com/w3c/tidy-html5) over the spec before doing pull requests instead. That way, Editors don't need to worry about line length and indenting and tidy can just take care of that automagically. 

Other specs in the WG are already using tidy (e.g., web-alarms, manifest, raw-sockets)

If that is ok, I would like to set this up. 

PS: if there is anyone good with bash, it would be great if we had a [git hook](http://git-scm.com/book/en/Customizing-Git-Git-Hooks) for this.

**Comment by marcoscaceres** [comment]
work in progress

**Comment by zolkis** [comment]
Could we use tidy without the indenting? It bloats e.g. event handler tables beyond imagination.

**Comment by marcoscaceres** [comment]
I see what you mean. I can see if I can reduce the indenting to 1 space and simplify the table markup a bit. That should make it a bit more legible, hopefully.
