### ISSUE TITLE
disconnect reasons need to be defined as an enum

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/telephony#68]

**Comment by zolkis** [comment]
We can define it as dictionary, but there should be a way for an implementation to add platform-specific strings there, too. There are so many disconnect reason descriptions, and so divergent, that I thought a DOMString would be the best. Ofono has solved this problem by only telling the source of the disconnection: "local" (hung up by user), "network" (disconnected by network) and "remote" (hung up by remote end).

**Comment by marcoscaceres** [comment]
The above three (local, network, remote) might be something we can work with.

**Comment by zolkis** [comment]
For start, yes. I expect to support more definitions later. As an alternative, we can also keep the current list as enumeration, and then implementations should do a mapping, supporting at least the 3 basic reasons above.
