### ISSUE TITLE
It's not necessary to define any EventHandler attributes

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/telephony#69]
Because of the the way EventHandlers are wired up, it is not necessary for them to be defined in the same way as other attributes. We just need a table that looks like this:

![screen shot 2013-05-24 at 11 14 07 am](https://f.cloud.github.com/assets/870154/559799/f5f12c2a-c45a-11e2-83d1-71b73aed95bc.png)

The actual prose that fires the events needs to be defined in a life cycle section (that lifecycle text is already in the spec, just needs to be brought together more clearly).

**Comment by zolkis** [comment]
OK.

**Comment by zolkis** [comment]
I started work on adding these tables.

**Comment by marcoscaceres** [comment]
@zolkis If possible, can you ping me on IRC on the w3c server (#sysapps channel)? had some thoughts about these wanted to discuss with you.

**Comment by zolkis** [comment]
PR #83 closes this.

**Comment by efullea** [comment]
Event handler table still missing in the ConferenceCall interface

**Comment by zolkis** [comment]
Indeed. Will update.

**Comment by zolkis** [comment]
BTW we will have the same information in 3 different places, making the spec bloated.

**Comment by marcoscaceres** [comment]
Once we disable the legacyStyle, the duplication will go away. However, that will take a few days of fairly boring work to do, so I'm keen to put that off until after the 18th. Is that ok?

**Comment by zolkis** [comment]
Of course.

**Comment by marcoscaceres** [comment]
Reopening this one, as we need to do this work regardless.

**Comment by marcoscaceres** [comment]
Work in progress
