### ISSUE TITLE
Checking remoteParty phone number

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/telephony#70]
When dial() is invoked, it's not clear what to do if the following string is sent:

```
navigator.telephony.dial("hello there!  عربي/عربى ")
```

In other words, should telephone numbers adhere to the appropriate part of [RFC3996](http://www.ietf.org/rfc/rfc3966.txt):

```
   telephone-subscriber = global-number / local-number
   global-number        = global-number-digits *par
   local-number         = local-number-digits *par context *par
   par                  = parameter / extension / isdn-subaddress
   isdn-subaddress      = ";isub=" 1*uric
   extension            = ";ext=" 1*phonedigit
   context              = ";phone-context=" descriptor
   descriptor           = domainname / global-number-digits
   global-number-digits = "+" *phonedigit DIGIT *phonedigit
   local-number-digits  = *phonedigit-hex (HEXDIG / "*" / "#")*phonedigit-hex
   domainname           = *( domainlabel "." ) toplabel [ "." ]
   domainlabel          = alphanum
                          / alphanum *( alphanum / "-" ) alphanum
   toplabel             = ALPHA / ALPHA *( alphanum / "-" ) alphanum
   parameter            = ";" pname ["=" pvalue ]
   pname                = 1*( alphanum / "-" )
   pvalue               = 1*paramchar
   paramchar            = param-unreserved / unreserved / pct-encoded
   unreserved           = alphanum / mark
   mark                 = "-" / "_" / "." / "!" / "~" / "*" /
                          "'" / "(" / ")"
   pct-encoded          = "%" HEXDIG HEXDIG
   param-unreserved     = "[" / "]" / "/" / ":" / "&" / "+" / "$"
   phonedigit           = DIGIT / [ visual-separator ]
   phonedigit-hex       = HEXDIG / "*" / "#" / [ visual-separator ]
   visual-separator     = "-" / "." / "(" / ")"
   alphanum             = ALPHA / DIGIT
   reserved             = ";" / "/" / "?" / ":" / "@" / "&" /
                          "=" / "+" / "$" / ","
   uric                 = reserved / unreserved / pct-encoded
```

**Comment by zolkis** [comment]
I thought that is the responsibility of the implementation. Is there a reason to hard specify it in the spec? The remotePartyId should support phone numbers, SIP and XMPP addresses, and possibly other remote end identifiers. It is actually telephony service specific, and the exact details on how to parse it is owned by the telephony service. 

I would also ask others what would they prefer. Of course we could say that in this version we limit to phone numbers, mentioning possible later extension to support SIP and XMPP remote parties (they have references for the namespace and validation).

**Comment by zolkis** [comment]
The way telephony numbers are specified in <a href='http://ofono.org'>oFono</a> documentation:

<pre>            The number must be a string in the following format:
                        [+][0-9*#]{1,80}
            In other words, it must be a non-empty string
            optionally prefixed with a '+' followed by 1 to 80
            characters.  The character set can contain numbers,
            '*' and '#'.  Besides this sanity checking no further
            number validation is performed.  It is assumed the
            network will perform further validation.  The optional
            '+' denotes an international number format.  For
            example:
                +15551234567 - International format
                5551234567 - National / Uknown format
</pre>

But as said, in the future the remote party identifiers may include any string understood by the telephony service, i.e. the telephony service is expected to do the validation. Is it enough to mention this, and as example cite the phone numbers' use case?

**Comment by marcoscaceres** [comment]
This is now clarified in the spec... the telephony service deals with it.
