### ISSUE TITLE
remove 'inConference' from TelephonyCall

### ISSUE THREAD

**Issue by zolkis** [sysapps/telephony#74]
Since 'conferenceId' can provide exactly the same information, the 'inConference' property is not needed. So instead of

<pre>if(call.inConference)</pre>

one could write

<pre>if(call.conferenceId)</pre>

Therefore the property could be removed.

**Comment by marcoscaceres** [comment]
the problem is that conferenceID is not guaranteed to not return an empty string. If we put that into the spec, then this should be ok.

**Comment by zolkis** [comment]
OK, I update the description.

**Comment by marcoscaceres** [comment]
sounds good! :)

**Comment by marcoscaceres** [comment]
Can this be closed?

**Comment by zolkis** [comment]
yes
