### ISSUE TITLE
Fix startTone method description

### ISSUE THREAD

**Issue by efullea** [sysapps/telephony#88]
-Description of 'tone' parameter states it is a sequence of the following characters (0-9; A-D; *; #), whereas it shuld be just one of these characters
-Description of 'param' parameter should state that 'delay' should be ignored

**Comment by zolkis** [comment]
Thanks Eduardo, work started.

**Comment by zolkis** [comment]
Note that the 'gap' parameter is used, it is the 'duration' parameter which is ignored.

**Comment by efullea** [comment]
Do we really want to delay the start of that long tone according to the 'gap' parameter? IMO this parameter just makes sense when automatically emiting a sequence of tones (using sendTones), but not in this case. Wjhat is the use case behind?

**Comment by zolkis** [comment]
Same reasoning as in #102

**Comment by marcoscaceres** [comment]
I think maybe we should just clarify the text a little bit. @efullea concern is valid in that it might confuse readers - though @zolkis wording is correct. Should we add a small note or example?

**Comment by zolkis** [comment]
I can add clarification to the text - feel free to take it forward then.
