### ISSUE TITLE
Links to Error Steps are not working

### ISSUE THREAD

**Issue by efullea** [sysapps/telephony#90]
Actually I cannot find the description of those error steps

**Comment by zolkis** [comment]
OK, have to look up when did it disappear :)

**Comment by marcoscaceres** [comment]
Oh, got rid of generic error handling a little while ago. I was intending to fix that today as part of an editorial cleanup.

**Comment by marcoscaceres** [comment]
So, here is the commit I did to removed it:

https://github.com/sysapps/telephony/commit/7cbec66c021cb5945412cc33d6aeb027ea0e0d72

I'm going to add it back in now for the FPWD.
