### ISSUE TITLE
The description of the join method is assuming the method has a remotePartiy parameter

### ISSUE THREAD

**Issue by efullea** [sysapps/telephony#91]
See following excerpt:

"The join method when invoked MUST run the following steps:
    If the remoteParty property is equal to the remoteParty parameter of the method call, ...."

**Comment by zolkis** [comment]
Thanks, good catch. I will fix this in relation with the API redesign suggested in #87

**Comment by efullea** [comment]
OK, great. Actually I think we should also remove the references to VoIP services as they are not being handled in this version of the API

**Comment by zolkis** [comment]
I will look into that, but for instance in the description of telephony services IMO it makes sense, since it is a design target, even at this point. In addition, there have been explicit questions on the F2F on how are we going to handle e.g. SIP/LTE. So this gives a hint of direction.

**Comment by efullea** [comment]
Seems like PR#109 accidentally reverted part of the changes

**Comment by zolkis** [comment]
thanks for checking
