### ISSUE TITLE
Call states not applicable to ConferenceCall objects

### ISSUE THREAD

**Issue by efullea** [sysapps/telephony#93]
It should be mentioned which call states from 'CallState' are not applicable to ConferenceCall objects

**Comment by zolkis** [comment]
Isn't enough to mention which do? And also, that the rest don't.

**Comment by efullea** [comment]
Either way, but it may be shorter to mention which of them do not apply.

**Comment by marcoscaceres** [comment]
I think which do is better from a spec maintainability point of view.

**Comment by efullea** [comment]
If I am not wrong, just the following states apply to ConferenceCall objects: "active",  "holding",  "held", "resuming", "disconnecting", "disconnected", "joining", "splitting". 
BTW, in the steps describing the "split" method it is not stated that the ConferenceCall should transition to "splitting" state and back to "active" afterwards. Should we?

**Comment by zolkis** [comment]
In the API spec there is the following comment about multiparty states:

<pre>
    Multiparty call sequences and states
    ====================================
    GSM TS 24.084.
    "There are four auxiliary states associated with the MPTY service:
    - Idle;
    - MPTY request; A request has been made to add this call to the MPTY.
    - Call in MPTY; This call is in the MPTY.
    - Split request; A request has been made to remove this call from the MPTY.
    These Auxiliary states apply in addition to the GSM 04.08 call control
    states and the GSM 04.83 call hold states. Thus for example, an active
    call in a held MPTY has the state (Active, Call held, Call in MPTY).
    Not all states are allowed, for example an MPTY cannot be split while
    it is held, so (Active, Call held, Split request) is forbidden."
    
    Instead of this, we offer a model when states describe valid multiparty
    states. Valid state transitions for a multiparty call are:
    * joining -> active
    * active -> holding -> held
    * held -> resuming -> active (connected)
    * any state -> [disconnecting]-> disconnected
</pre>

The GSM spec thus puts only the split call to the 'splitting' state, not the conference call, which remains active, until the call is split, the conference call is put on hold, and the split call is activated. Therefore my understanding is that the API spec should not mandate a conference call state transition for active-splitting-active.

**Comment by zolkis** [comment]
I just checked, and the spec clearly states which states must be supported, see CallState description.

Moreover, the events in ConferenceCall also clearly tell which states are supported.

Then, now I also see the table with supported states. Note that 'splitting' state is there too for ConferenceCall, but the GSM spec does not mention is, nor does CDMA support it currently. So there is a possibility that an implementation may use it, but it is not normative (implementations are not compelled to use it).

Are there more questions, or could we close this issue?

**Comment by efullea** [comment]
Description in CallState states something different, namely which of the states are soft states and thus may not be supported by some implementations and which are hard states and must be supported (BTW I miss a mention to 'redirecting' similar to the one to 'transfering'). And in fact it is related to TelephonyCall objects, not to ConferenceCall objects.

We really need to mention which of these states apply to ConferenceCall objects and which not. As you mention, this info could be inferred from the events, but that is not enough.

And please do not close issues as quickly. My response time is sometimes longer than a few hours ;-) and other may want to comment as well.

**Comment by zolkis** [comment]
Do you see need for more description than what there is in 11.3 ?

**Comment by efullea** [comment]
Actually it is enough. Thanks.
